# Generated by Django 2.2.9 on 2021-02-17 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_auto_20210213_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='foto',
        ),
    ]
